/*
 * IDENTIFICATION:
 * stub generated Thu Dec 13 19:13:56 2018
 * with a MiG generated by bootstrap_cmds-96.20.2.200.4
 * OPTIONS: 
 */

/* Module capsd */

#define	__MIG_check__Request__capsd_subsystem__ 1

#include <string.h>
#include <mach/ndr.h>
#include <mach/boolean.h>
#include <mach/kern_return.h>
#include <mach/notify.h>
#include <mach/mach_types.h>
#include <mach/message.h>
#include <mach/mig_errors.h>
#include <mach/port.h>
	
/* BEGIN VOUCHER CODE */

#ifndef KERNEL
#if defined(__has_include)
#if __has_include(<mach/mig_voucher_support.h>)
#ifndef USING_VOUCHERS
#define USING_VOUCHERS
#endif
#ifndef __VOUCHER_FORWARD_TYPE_DECLS__
#define __VOUCHER_FORWARD_TYPE_DECLS__
#ifdef __cplusplus
extern "C" {
#endif
	extern boolean_t voucher_mach_msg_set(mach_msg_header_t *msg) __attribute__((weak_import));
#ifdef __cplusplus
}
#endif
#endif // __VOUCHER_FORWARD_TYPE_DECLS__
#endif // __has_include(<mach/mach_voucher_types.h>)
#endif // __has_include
#endif // !KERNEL
	
/* END VOUCHER CODE */

	
/* BEGIN MIG_STRNCPY_ZEROFILL CODE */

#if defined(__has_include)
#if __has_include(<mach/mig_strncpy_zerofill_support.h>)
#ifndef USING_MIG_STRNCPY_ZEROFILL
#define USING_MIG_STRNCPY_ZEROFILL
#endif
#ifndef __MIG_STRNCPY_ZEROFILL_FORWARD_TYPE_DECLS__
#define __MIG_STRNCPY_ZEROFILL_FORWARD_TYPE_DECLS__
#ifdef __cplusplus
extern "C" {
#endif
	extern int mig_strncpy_zerofill(char *dest, const char *src, int len) __attribute__((weak_import));
#ifdef __cplusplus
}
#endif
#endif /* __MIG_STRNCPY_ZEROFILL_FORWARD_TYPE_DECLS__ */
#endif /* __has_include(<mach/mig_strncpy_zerofill_support.h>) */
#endif /* __has_include */
	
/* END MIG_STRNCPY_ZEROFILL CODE */


#include <mach/std_types.h>
#include <mach/mig.h>
#include <mach/mig.h>
#include <mach/mach_types.h>
#include <mach_debug/mach_debug_types.h>
#include "../common/types.h"

#ifndef	mig_internal
#define	mig_internal	static __inline__
#endif	/* mig_internal */

#ifndef	mig_external
#define mig_external
#endif	/* mig_external */

#if	!defined(__MigTypeCheck) && defined(TypeCheck)
#define	__MigTypeCheck		TypeCheck	/* Legacy setting */
#endif	/* !defined(__MigTypeCheck) */

#if	!defined(__MigKernelSpecificCode) && defined(_MIG_KERNEL_SPECIFIC_CODE_)
#define	__MigKernelSpecificCode	_MIG_KERNEL_SPECIFIC_CODE_	/* Legacy setting */
#endif	/* !defined(__MigKernelSpecificCode) */

#ifndef	LimitCheck
#define	LimitCheck 0
#endif	/* LimitCheck */

#ifndef	min
#define	min(a,b)  ( ((a) < (b))? (a): (b) )
#endif	/* min */

#if !defined(_WALIGN_)
#define _WALIGN_(x) (((x) + 3) & ~3)
#endif /* !defined(_WALIGN_) */

#if !defined(_WALIGNSZ_)
#define _WALIGNSZ_(x) _WALIGN_(sizeof(x))
#endif /* !defined(_WALIGNSZ_) */

#ifndef	UseStaticTemplates
#define	UseStaticTemplates	0
#endif	/* UseStaticTemplates */

#ifndef	__DeclareRcvRpc
#define	__DeclareRcvRpc(_NUM_, _NAME_)
#endif	/* __DeclareRcvRpc */

#ifndef	__BeforeRcvRpc
#define	__BeforeRcvRpc(_NUM_, _NAME_)
#endif	/* __BeforeRcvRpc */

#ifndef	__AfterRcvRpc
#define	__AfterRcvRpc(_NUM_, _NAME_)
#endif	/* __AfterRcvRpc */

#ifndef	__DeclareRcvSimple
#define	__DeclareRcvSimple(_NUM_, _NAME_)
#endif	/* __DeclareRcvSimple */

#ifndef	__BeforeRcvSimple
#define	__BeforeRcvSimple(_NUM_, _NAME_)
#endif	/* __BeforeRcvSimple */

#ifndef	__AfterRcvSimple
#define	__AfterRcvSimple(_NUM_, _NAME_)
#endif	/* __AfterRcvSimple */

#define novalue void

#define msgh_request_port	msgh_local_port
#define MACH_MSGH_BITS_REQUEST(bits)	MACH_MSGH_BITS_LOCAL(bits)
#define msgh_reply_port		msgh_remote_port
#define MACH_MSGH_BITS_REPLY(bits)	MACH_MSGH_BITS_REMOTE(bits)

#define MIG_RETURN_ERROR(X, code)	{\
				((mig_reply_error_t *)X)->RetCode = code;\
				((mig_reply_error_t *)X)->NDR = NDR_record;\
				return;\
				}

/* typedefs for all requests */

#ifndef __Request__capsd_subsystem__defined
#define __Request__capsd_subsystem__defined

#ifdef  __MigPackStructs
#pragma pack(4)
#endif
	typedef struct {
		mach_msg_header_t Head;
		NDR_record_t NDR;
		audit_token_t target;
		mach_msg_type_number_t operationOffset; /* MiG doesn't use it */
		mach_msg_type_number_t operationCnt;
		char operation[1024];
		mach_msg_type_number_t argOffset; /* MiG doesn't use it */
		mach_msg_type_number_t argCnt;
		char arg[1024];
	} __Request__grant_capability_t __attribute__((unused));
#ifdef  __MigPackStructs
#pragma pack()
#endif

#ifdef  __MigPackStructs
#pragma pack(4)
#endif
	typedef struct {
		mach_msg_header_t Head;
		NDR_record_t NDR;
		int pid;
		mach_msg_type_number_t operationOffset; /* MiG doesn't use it */
		mach_msg_type_number_t operationCnt;
		char operation[1024];
		mach_msg_type_number_t argOffset; /* MiG doesn't use it */
		mach_msg_type_number_t argCnt;
		char arg[1024];
	} __Request__has_capability_t __attribute__((unused));
#ifdef  __MigPackStructs
#pragma pack()
#endif
#endif /* !__Request__capsd_subsystem__defined */

/* typedefs for all replies */

#ifndef __Reply__capsd_subsystem__defined
#define __Reply__capsd_subsystem__defined

#ifdef  __MigPackStructs
#pragma pack(4)
#endif
	typedef struct {
		mach_msg_header_t Head;
		NDR_record_t NDR;
		kern_return_t RetCode;
	} __Reply__grant_capability_t __attribute__((unused));
#ifdef  __MigPackStructs
#pragma pack()
#endif

#ifdef  __MigPackStructs
#pragma pack(4)
#endif
	typedef struct {
		mach_msg_header_t Head;
		NDR_record_t NDR;
		kern_return_t RetCode;
		int result;
	} __Reply__has_capability_t __attribute__((unused));
#ifdef  __MigPackStructs
#pragma pack()
#endif
#endif /* !__Reply__capsd_subsystem__defined */


/* union of all replies */

#ifndef __ReplyUnion__capsd_subsystem__defined
#define __ReplyUnion__capsd_subsystem__defined
union __ReplyUnion__capsd_subsystem {
	__Reply__grant_capability_t Reply_grant_capability;
	__Reply__has_capability_t Reply_has_capability;
};
#endif /* __RequestUnion__capsd_subsystem__defined */
/* Forward Declarations */


mig_internal novalue _Xgrant_capability
	(mach_msg_header_t *InHeadP, mach_msg_header_t *OutHeadP);

mig_internal novalue _Xhas_capability
	(mach_msg_header_t *InHeadP, mach_msg_header_t *OutHeadP);


#if ( __MigTypeCheck )
#if __MIG_check__Request__capsd_subsystem__
#if !defined(__MIG_check__Request__grant_capability_t__defined)
#define __MIG_check__Request__grant_capability_t__defined

mig_internal kern_return_t __MIG_check__Request__grant_capability_t(__attribute__((__unused__)) __Request__grant_capability_t *In0P, __attribute__((__unused__)) __Request__grant_capability_t **In1PP)
{

	typedef __Request__grant_capability_t __Request;
	__Request *In1P;
#if	__MigTypeCheck
	unsigned int msgh_size;
#endif	/* __MigTypeCheck */
	unsigned int msgh_size_delta;

#if	__MigTypeCheck
	msgh_size = In0P->Head.msgh_size;
	if ((In0P->Head.msgh_bits & MACH_MSGH_BITS_COMPLEX) ||
	    (msgh_size < (mach_msg_size_t)(sizeof(__Request) - 2048)) ||  (msgh_size > (mach_msg_size_t)sizeof(__Request)))
		return MIG_BAD_ARGUMENTS;
#endif	/* __MigTypeCheck */

#if defined(__NDR_convert__int_rep__Request__grant_capability_t__operationCnt__defined)
	if (In0P->NDR.int_rep != NDR_record.int_rep)
		__NDR_convert__int_rep__Request__grant_capability_t__operationCnt(&In0P->operationCnt, In0P->NDR.int_rep);
#endif	/* __NDR_convert__int_rep__Request__grant_capability_t__operationCnt__defined */
	msgh_size_delta = _WALIGN_(In0P->operationCnt);
#if	__MigTypeCheck
	if ( In0P->operationCnt > 1024 )
		return MIG_BAD_ARGUMENTS;
	if (((msgh_size - (mach_msg_size_t)(sizeof(__Request) - 2048)) < In0P->operationCnt) ||
	    (msgh_size < (mach_msg_size_t)(sizeof(__Request) - 2048) + _WALIGN_(In0P->operationCnt)))
		return MIG_BAD_ARGUMENTS;
	msgh_size -= msgh_size_delta;
#endif	/* __MigTypeCheck */

	*In1PP = In1P = (__Request *) ((pointer_t) In0P + msgh_size_delta - 1024);

#if defined(__NDR_convert__int_rep__Request__grant_capability_t__argCnt__defined)
	if (In0P->NDR.int_rep != NDR_record.int_rep)
		__NDR_convert__int_rep__Request__grant_capability_t__argCnt(&In1P->argCnt, In1P->NDR.int_rep);
#endif	/* __NDR_convert__int_rep__Request__grant_capability_t__argCnt__defined */
#if	__MigTypeCheck
	if ( In1P->argCnt > 1024 )
		return MIG_BAD_ARGUMENTS;
	if (((msgh_size - (mach_msg_size_t)(sizeof(__Request) - 2048)) < In1P->argCnt) ||
	    (msgh_size != (mach_msg_size_t)(sizeof(__Request) - 2048) + _WALIGN_(In1P->argCnt)))
		return MIG_BAD_ARGUMENTS;
#endif	/* __MigTypeCheck */

#if __MigTypeCheck
	{
		char * msg_limit = ((char *) In0P) + In0P->Head.msgh_size;
		size_t memchr_limit;

		memchr_limit = min((msg_limit - In0P->operation),  1024);
		if (( memchr(In0P->operation, '\0', memchr_limit) == NULL ))
			return MIG_BAD_ARGUMENTS; // string length exceeds buffer length!
		memchr_limit = min((msg_limit - In1P->arg),  1024);
		if (( memchr(In1P->arg, '\0', memchr_limit) == NULL ))
			return MIG_BAD_ARGUMENTS; // string length exceeds buffer length!
	}
#endif	/* __MigTypeCheck */

	return MACH_MSG_SUCCESS;
}
#endif /* !defined(__MIG_check__Request__grant_capability_t__defined) */
#endif /* __MIG_check__Request__capsd_subsystem__ */
#endif /* ( __MigTypeCheck ) */


/* Routine grant_capability */
#ifdef	mig_external
mig_external
#else
extern
#endif	/* mig_external */
kern_return_t grant_capability
(
	mach_port_t server,
	audit_token_t token,
	audit_token_t target,
	string operation,
	string arg
);

/* Routine grant_capability */
mig_internal novalue _Xgrant_capability
	(mach_msg_header_t *InHeadP, mach_msg_header_t *OutHeadP)
{

#ifdef  __MigPackStructs
#pragma pack(4)
#endif
	typedef struct {
		mach_msg_header_t Head;
		NDR_record_t NDR;
		audit_token_t target;
		mach_msg_type_number_t operationOffset; /* MiG doesn't use it */
		mach_msg_type_number_t operationCnt;
		char operation[1024];
		mach_msg_type_number_t argOffset; /* MiG doesn't use it */
		mach_msg_type_number_t argCnt;
		char arg[1024];
		mach_msg_max_trailer_t trailer;
	} Request __attribute__((unused));
#ifdef  __MigPackStructs
#pragma pack()
#endif
	typedef __Request__grant_capability_t __Request;
	typedef __Reply__grant_capability_t Reply __attribute__((unused));

	/*
	 * typedef struct {
	 * 	mach_msg_header_t Head;
	 * 	NDR_record_t NDR;
	 * 	kern_return_t RetCode;
	 * } mig_reply_error_t;
	 */

	Request *In0P = (Request *) InHeadP;
	Request *In1P;
	Reply *OutP = (Reply *) OutHeadP;
	mach_msg_max_trailer_t *TrailerP;
#if	__MigTypeCheck
	unsigned int trailer_size;
#endif	/* __MigTypeCheck */
#ifdef	__MIG_check__Request__grant_capability_t__defined
	kern_return_t check_result;
#endif	/* __MIG_check__Request__grant_capability_t__defined */

	__DeclareRcvRpc(733100, "grant_capability")
	__BeforeRcvRpc(733100, "grant_capability")

#if	defined(__MIG_check__Request__grant_capability_t__defined)
	check_result = __MIG_check__Request__grant_capability_t((__Request *)In0P, (__Request **)&In1P);
	if (check_result != MACH_MSG_SUCCESS)
		{ MIG_RETURN_ERROR(OutP, check_result); }
#endif	/* defined(__MIG_check__Request__grant_capability_t__defined) */

	TrailerP = (mach_msg_max_trailer_t *)((vm_offset_t)In0P +
		round_msg(In0P->Head.msgh_size));
	if (TrailerP->msgh_trailer_type != MACH_MSG_TRAILER_FORMAT_0)
		{ MIG_RETURN_ERROR(In0P, MIG_TRAILER_ERROR); }
#if	__MigTypeCheck
	trailer_size = TrailerP->msgh_trailer_size -
		(mach_msg_size_t)(sizeof(mach_msg_trailer_type_t) - sizeof(mach_msg_trailer_size_t));
#endif	/* __MigTypeCheck */
#if	__MigTypeCheck
	if (trailer_size < (mach_msg_size_t)sizeof(audit_token_t))
		{ MIG_RETURN_ERROR(OutP, MIG_TRAILER_ERROR); }
	trailer_size -= (mach_msg_size_t)sizeof(audit_token_t);
#endif	/* __MigTypeCheck */
	OutP->RetCode = grant_capability(In0P->Head.msgh_request_port, TrailerP->msgh_audit, In0P->target, In0P->operation, In1P->arg);

	OutP->NDR = NDR_record;


	__AfterRcvRpc(733100, "grant_capability")
}

#if ( __MigTypeCheck )
#if __MIG_check__Request__capsd_subsystem__
#if !defined(__MIG_check__Request__has_capability_t__defined)
#define __MIG_check__Request__has_capability_t__defined

mig_internal kern_return_t __MIG_check__Request__has_capability_t(__attribute__((__unused__)) __Request__has_capability_t *In0P, __attribute__((__unused__)) __Request__has_capability_t **In1PP)
{

	typedef __Request__has_capability_t __Request;
	__Request *In1P;
#if	__MigTypeCheck
	unsigned int msgh_size;
#endif	/* __MigTypeCheck */
	unsigned int msgh_size_delta;

#if	__MigTypeCheck
	msgh_size = In0P->Head.msgh_size;
	if ((In0P->Head.msgh_bits & MACH_MSGH_BITS_COMPLEX) ||
	    (msgh_size < (mach_msg_size_t)(sizeof(__Request) - 2048)) ||  (msgh_size > (mach_msg_size_t)sizeof(__Request)))
		return MIG_BAD_ARGUMENTS;
#endif	/* __MigTypeCheck */

#if defined(__NDR_convert__int_rep__Request__has_capability_t__operationCnt__defined)
	if (In0P->NDR.int_rep != NDR_record.int_rep)
		__NDR_convert__int_rep__Request__has_capability_t__operationCnt(&In0P->operationCnt, In0P->NDR.int_rep);
#endif	/* __NDR_convert__int_rep__Request__has_capability_t__operationCnt__defined */
	msgh_size_delta = _WALIGN_(In0P->operationCnt);
#if	__MigTypeCheck
	if ( In0P->operationCnt > 1024 )
		return MIG_BAD_ARGUMENTS;
	if (((msgh_size - (mach_msg_size_t)(sizeof(__Request) - 2048)) < In0P->operationCnt) ||
	    (msgh_size < (mach_msg_size_t)(sizeof(__Request) - 2048) + _WALIGN_(In0P->operationCnt)))
		return MIG_BAD_ARGUMENTS;
	msgh_size -= msgh_size_delta;
#endif	/* __MigTypeCheck */

	*In1PP = In1P = (__Request *) ((pointer_t) In0P + msgh_size_delta - 1024);

#if defined(__NDR_convert__int_rep__Request__has_capability_t__argCnt__defined)
	if (In0P->NDR.int_rep != NDR_record.int_rep)
		__NDR_convert__int_rep__Request__has_capability_t__argCnt(&In1P->argCnt, In1P->NDR.int_rep);
#endif	/* __NDR_convert__int_rep__Request__has_capability_t__argCnt__defined */
#if	__MigTypeCheck
	if ( In1P->argCnt > 1024 )
		return MIG_BAD_ARGUMENTS;
	if (((msgh_size - (mach_msg_size_t)(sizeof(__Request) - 2048)) < In1P->argCnt) ||
	    (msgh_size != (mach_msg_size_t)(sizeof(__Request) - 2048) + _WALIGN_(In1P->argCnt)))
		return MIG_BAD_ARGUMENTS;
#endif	/* __MigTypeCheck */

#if __MigTypeCheck
	{
		char * msg_limit = ((char *) In0P) + In0P->Head.msgh_size;
		size_t memchr_limit;

		memchr_limit = min((msg_limit - In0P->operation),  1024);
		if (( memchr(In0P->operation, '\0', memchr_limit) == NULL ))
			return MIG_BAD_ARGUMENTS; // string length exceeds buffer length!
		memchr_limit = min((msg_limit - In1P->arg),  1024);
		if (( memchr(In1P->arg, '\0', memchr_limit) == NULL ))
			return MIG_BAD_ARGUMENTS; // string length exceeds buffer length!
	}
#endif	/* __MigTypeCheck */

	return MACH_MSG_SUCCESS;
}
#endif /* !defined(__MIG_check__Request__has_capability_t__defined) */
#endif /* __MIG_check__Request__capsd_subsystem__ */
#endif /* ( __MigTypeCheck ) */


/* Routine has_capability */
#ifdef	mig_external
mig_external
#else
extern
#endif	/* mig_external */
kern_return_t has_capability
(
	mach_port_t server,
	int pid,
	string operation,
	string arg,
	int *result
);

/* Routine has_capability */
mig_internal novalue _Xhas_capability
	(mach_msg_header_t *InHeadP, mach_msg_header_t *OutHeadP)
{

#ifdef  __MigPackStructs
#pragma pack(4)
#endif
	typedef struct {
		mach_msg_header_t Head;
		NDR_record_t NDR;
		int pid;
		mach_msg_type_number_t operationOffset; /* MiG doesn't use it */
		mach_msg_type_number_t operationCnt;
		char operation[1024];
		mach_msg_type_number_t argOffset; /* MiG doesn't use it */
		mach_msg_type_number_t argCnt;
		char arg[1024];
		mach_msg_trailer_t trailer;
	} Request __attribute__((unused));
#ifdef  __MigPackStructs
#pragma pack()
#endif
	typedef __Request__has_capability_t __Request;
	typedef __Reply__has_capability_t Reply __attribute__((unused));

	/*
	 * typedef struct {
	 * 	mach_msg_header_t Head;
	 * 	NDR_record_t NDR;
	 * 	kern_return_t RetCode;
	 * } mig_reply_error_t;
	 */

	Request *In0P = (Request *) InHeadP;
	Request *In1P;
	Reply *OutP = (Reply *) OutHeadP;
#ifdef	__MIG_check__Request__has_capability_t__defined
	kern_return_t check_result;
#endif	/* __MIG_check__Request__has_capability_t__defined */

	__DeclareRcvRpc(733101, "has_capability")
	__BeforeRcvRpc(733101, "has_capability")

#if	defined(__MIG_check__Request__has_capability_t__defined)
	check_result = __MIG_check__Request__has_capability_t((__Request *)In0P, (__Request **)&In1P);
	if (check_result != MACH_MSG_SUCCESS)
		{ MIG_RETURN_ERROR(OutP, check_result); }
#endif	/* defined(__MIG_check__Request__has_capability_t__defined) */

	OutP->RetCode = has_capability(In0P->Head.msgh_request_port, In0P->pid, In0P->operation, In1P->arg, &OutP->result);
	if (OutP->RetCode != KERN_SUCCESS) {
		MIG_RETURN_ERROR(OutP, OutP->RetCode);
	}

	OutP->NDR = NDR_record;


	OutP->Head.msgh_size = (mach_msg_size_t)(sizeof(Reply));
	__AfterRcvRpc(733101, "has_capability")
}


#ifdef	mig_external
mig_external
#else
extern
#endif	/* mig_external */
boolean_t capsd_server(
		mach_msg_header_t *InHeadP,
		mach_msg_header_t *OutHeadP);

#ifdef	mig_external
mig_external
#else
extern
#endif	/* mig_external */
mig_routine_t capsd_server_routine(
		mach_msg_header_t *InHeadP);


/* Description of this subsystem, for use in direct RPC */
const struct capsd_subsystem {
	mig_server_routine_t 	server;	/* Server routine */
	mach_msg_id_t	start;	/* Min routine number */
	mach_msg_id_t	end;	/* Max routine number + 1 */
	unsigned int	maxsize;	/* Max msg size */
	vm_address_t	reserved;	/* Reserved */
	struct routine_descriptor	/*Array of routine descriptors */
		routine[2];
} capsd_subsystem = {
	capsd_server_routine,
	733100,
	733102,
	(mach_msg_size_t)sizeof(union __ReplyUnion__capsd_subsystem),
	(vm_address_t)0,
	{
          { (mig_impl_routine_t) 0,
          (mig_stub_routine_t) _Xgrant_capability, 19, 0, (routine_arg_descriptor_t)0, (mach_msg_size_t)sizeof(__Reply__grant_capability_t)},
          { (mig_impl_routine_t) 0,
          (mig_stub_routine_t) _Xhas_capability, 5, 0, (routine_arg_descriptor_t)0, (mach_msg_size_t)sizeof(__Reply__has_capability_t)},
	}
};

mig_external boolean_t capsd_server
	(mach_msg_header_t *InHeadP, mach_msg_header_t *OutHeadP)
{
	/*
	 * typedef struct {
	 * 	mach_msg_header_t Head;
	 * 	NDR_record_t NDR;
	 * 	kern_return_t RetCode;
	 * } mig_reply_error_t;
	 */

	register mig_routine_t routine;

	OutHeadP->msgh_bits = MACH_MSGH_BITS(MACH_MSGH_BITS_REPLY(InHeadP->msgh_bits), 0);
	OutHeadP->msgh_remote_port = InHeadP->msgh_reply_port;
	/* Minimal size: routine() will update it if different */
	OutHeadP->msgh_size = (mach_msg_size_t)sizeof(mig_reply_error_t);
	OutHeadP->msgh_local_port = MACH_PORT_NULL;
	OutHeadP->msgh_id = InHeadP->msgh_id + 100;
	OutHeadP->msgh_reserved = 0;

	if ((InHeadP->msgh_id > 733101) || (InHeadP->msgh_id < 733100) ||
	    ((routine = capsd_subsystem.routine[InHeadP->msgh_id - 733100].stub_routine) == 0)) {
		((mig_reply_error_t *)OutHeadP)->NDR = NDR_record;
		((mig_reply_error_t *)OutHeadP)->RetCode = MIG_BAD_ID;
		return FALSE;
	}
	(*routine) (InHeadP, OutHeadP);
	return TRUE;
}

mig_external mig_routine_t capsd_server_routine
	(mach_msg_header_t *InHeadP)
{
	register int msgh_id;

	msgh_id = InHeadP->msgh_id - 733100;

	if ((msgh_id > 1) || (msgh_id < 0))
		return 0;

	return capsd_subsystem.routine[msgh_id].stub_routine;
}
