/*
 * IDENTIFICATION:
 * stub generated Thu Dec 13 19:13:57 2018
 * with a MiG generated by bootstrap_cmds-96.20.2.200.4
 * OPTIONS: 
 */

/* Module shelld */

#define	__MIG_check__Request__shelld_subsystem__ 1

#include <string.h>
#include <mach/ndr.h>
#include <mach/boolean.h>
#include <mach/kern_return.h>
#include <mach/notify.h>
#include <mach/mach_types.h>
#include <mach/message.h>
#include <mach/mig_errors.h>
#include <mach/port.h>
	
/* BEGIN VOUCHER CODE */

#ifndef KERNEL
#if defined(__has_include)
#if __has_include(<mach/mig_voucher_support.h>)
#ifndef USING_VOUCHERS
#define USING_VOUCHERS
#endif
#ifndef __VOUCHER_FORWARD_TYPE_DECLS__
#define __VOUCHER_FORWARD_TYPE_DECLS__
#ifdef __cplusplus
extern "C" {
#endif
	extern boolean_t voucher_mach_msg_set(mach_msg_header_t *msg) __attribute__((weak_import));
#ifdef __cplusplus
}
#endif
#endif // __VOUCHER_FORWARD_TYPE_DECLS__
#endif // __has_include(<mach/mach_voucher_types.h>)
#endif // __has_include
#endif // !KERNEL
	
/* END VOUCHER CODE */

	
/* BEGIN MIG_STRNCPY_ZEROFILL CODE */

#if defined(__has_include)
#if __has_include(<mach/mig_strncpy_zerofill_support.h>)
#ifndef USING_MIG_STRNCPY_ZEROFILL
#define USING_MIG_STRNCPY_ZEROFILL
#endif
#ifndef __MIG_STRNCPY_ZEROFILL_FORWARD_TYPE_DECLS__
#define __MIG_STRNCPY_ZEROFILL_FORWARD_TYPE_DECLS__
#ifdef __cplusplus
extern "C" {
#endif
	extern int mig_strncpy_zerofill(char *dest, const char *src, int len) __attribute__((weak_import));
#ifdef __cplusplus
}
#endif
#endif /* __MIG_STRNCPY_ZEROFILL_FORWARD_TYPE_DECLS__ */
#endif /* __has_include(<mach/mig_strncpy_zerofill_support.h>) */
#endif /* __has_include */
	
/* END MIG_STRNCPY_ZEROFILL CODE */


#include <mach/std_types.h>
#include <mach/mig.h>
#include <mach/mig.h>
#include <mach/mach_types.h>
#include <mach_debug/mach_debug_types.h>
#include "../common/types.h"

#ifndef	mig_internal
#define	mig_internal	static __inline__
#endif	/* mig_internal */

#ifndef	mig_external
#define mig_external
#endif	/* mig_external */

#if	!defined(__MigTypeCheck) && defined(TypeCheck)
#define	__MigTypeCheck		TypeCheck	/* Legacy setting */
#endif	/* !defined(__MigTypeCheck) */

#if	!defined(__MigKernelSpecificCode) && defined(_MIG_KERNEL_SPECIFIC_CODE_)
#define	__MigKernelSpecificCode	_MIG_KERNEL_SPECIFIC_CODE_	/* Legacy setting */
#endif	/* !defined(__MigKernelSpecificCode) */

#ifndef	LimitCheck
#define	LimitCheck 0
#endif	/* LimitCheck */

#ifndef	min
#define	min(a,b)  ( ((a) < (b))? (a): (b) )
#endif	/* min */

#if !defined(_WALIGN_)
#define _WALIGN_(x) (((x) + 3) & ~3)
#endif /* !defined(_WALIGN_) */

#if !defined(_WALIGNSZ_)
#define _WALIGNSZ_(x) _WALIGN_(sizeof(x))
#endif /* !defined(_WALIGNSZ_) */

#ifndef	UseStaticTemplates
#define	UseStaticTemplates	0
#endif	/* UseStaticTemplates */

#ifndef	__DeclareRcvRpc
#define	__DeclareRcvRpc(_NUM_, _NAME_)
#endif	/* __DeclareRcvRpc */

#ifndef	__BeforeRcvRpc
#define	__BeforeRcvRpc(_NUM_, _NAME_)
#endif	/* __BeforeRcvRpc */

#ifndef	__AfterRcvRpc
#define	__AfterRcvRpc(_NUM_, _NAME_)
#endif	/* __AfterRcvRpc */

#ifndef	__DeclareRcvSimple
#define	__DeclareRcvSimple(_NUM_, _NAME_)
#endif	/* __DeclareRcvSimple */

#ifndef	__BeforeRcvSimple
#define	__BeforeRcvSimple(_NUM_, _NAME_)
#endif	/* __BeforeRcvSimple */

#ifndef	__AfterRcvSimple
#define	__AfterRcvSimple(_NUM_, _NAME_)
#endif	/* __AfterRcvSimple */

#define novalue void

#define msgh_request_port	msgh_local_port
#define MACH_MSGH_BITS_REQUEST(bits)	MACH_MSGH_BITS_LOCAL(bits)
#define msgh_reply_port		msgh_remote_port
#define MACH_MSGH_BITS_REPLY(bits)	MACH_MSGH_BITS_REMOTE(bits)

#define MIG_RETURN_ERROR(X, code)	{\
				((mig_reply_error_t *)X)->RetCode = code;\
				((mig_reply_error_t *)X)->NDR = NDR_record;\
				return;\
				}

/* typedefs for all requests */

#ifndef __Request__shelld_subsystem__defined
#define __Request__shelld_subsystem__defined

#ifdef  __MigPackStructs
#pragma pack(4)
#endif
	typedef struct {
		mach_msg_header_t Head;
		NDR_record_t NDR;
		mach_msg_type_number_t nameOffset; /* MiG doesn't use it */
		mach_msg_type_number_t nameCnt;
		char name[4096];
	} __Request__shelld_create_session_t __attribute__((unused));
#ifdef  __MigPackStructs
#pragma pack()
#endif

#ifdef  __MigPackStructs
#pragma pack(4)
#endif
	typedef struct {
		mach_msg_header_t Head;
		NDR_record_t NDR;
		mach_msg_type_number_t sessionOffset; /* MiG doesn't use it */
		mach_msg_type_number_t sessionCnt;
		char session[4096];
		mach_msg_type_number_t commandOffset; /* MiG doesn't use it */
		mach_msg_type_number_t commandCnt;
		char command[4096];
	} __Request__shell_exec_t __attribute__((unused));
#ifdef  __MigPackStructs
#pragma pack()
#endif

#ifdef  __MigPackStructs
#pragma pack(4)
#endif
	typedef struct {
		mach_msg_header_t Head;
		/* start of the kernel processed data */
		mach_msg_body_t msgh_body;
		mach_msg_port_descriptor_t listener;
		/* end of the kernel processed data */
		NDR_record_t NDR;
		mach_msg_type_number_t sessionOffset; /* MiG doesn't use it */
		mach_msg_type_number_t sessionCnt;
		char session[4096];
	} __Request__register_completion_listener_t __attribute__((unused));
#ifdef  __MigPackStructs
#pragma pack()
#endif

#ifdef  __MigPackStructs
#pragma pack(4)
#endif
	typedef struct {
		mach_msg_header_t Head;
		NDR_record_t NDR;
		mach_msg_type_number_t sessionOffset; /* MiG doesn't use it */
		mach_msg_type_number_t sessionCnt;
		char session[4096];
	} __Request__unregister_completion_listener_t __attribute__((unused));
#ifdef  __MigPackStructs
#pragma pack()
#endif
#endif /* !__Request__shelld_subsystem__defined */

/* typedefs for all replies */

#ifndef __Reply__shelld_subsystem__defined
#define __Reply__shelld_subsystem__defined

#ifdef  __MigPackStructs
#pragma pack(4)
#endif
	typedef struct {
		mach_msg_header_t Head;
		NDR_record_t NDR;
		kern_return_t RetCode;
	} __Reply__shelld_create_session_t __attribute__((unused));
#ifdef  __MigPackStructs
#pragma pack()
#endif

#ifdef  __MigPackStructs
#pragma pack(4)
#endif
	typedef struct {
		mach_msg_header_t Head;
		NDR_record_t NDR;
		kern_return_t RetCode;
	} __Reply__shell_exec_t __attribute__((unused));
#ifdef  __MigPackStructs
#pragma pack()
#endif

#ifdef  __MigPackStructs
#pragma pack(4)
#endif
	typedef struct {
		mach_msg_header_t Head;
		NDR_record_t NDR;
		kern_return_t RetCode;
	} __Reply__register_completion_listener_t __attribute__((unused));
#ifdef  __MigPackStructs
#pragma pack()
#endif

#ifdef  __MigPackStructs
#pragma pack(4)
#endif
	typedef struct {
		mach_msg_header_t Head;
		NDR_record_t NDR;
		kern_return_t RetCode;
	} __Reply__unregister_completion_listener_t __attribute__((unused));
#ifdef  __MigPackStructs
#pragma pack()
#endif
#endif /* !__Reply__shelld_subsystem__defined */


/* union of all replies */

#ifndef __ReplyUnion__shelld_subsystem__defined
#define __ReplyUnion__shelld_subsystem__defined
union __ReplyUnion__shelld_subsystem {
	__Reply__shelld_create_session_t Reply_shelld_create_session;
	__Reply__shell_exec_t Reply_shell_exec;
	__Reply__register_completion_listener_t Reply_register_completion_listener;
	__Reply__unregister_completion_listener_t Reply_unregister_completion_listener;
};
#endif /* __RequestUnion__shelld_subsystem__defined */
/* Forward Declarations */


mig_internal novalue _Xshelld_create_session
	(mach_msg_header_t *InHeadP, mach_msg_header_t *OutHeadP);

mig_internal novalue _Xshell_exec
	(mach_msg_header_t *InHeadP, mach_msg_header_t *OutHeadP);

mig_internal novalue _Xregister_completion_listener
	(mach_msg_header_t *InHeadP, mach_msg_header_t *OutHeadP);

mig_internal novalue _Xunregister_completion_listener
	(mach_msg_header_t *InHeadP, mach_msg_header_t *OutHeadP);


#if ( __MigTypeCheck )
#if __MIG_check__Request__shelld_subsystem__
#if !defined(__MIG_check__Request__shelld_create_session_t__defined)
#define __MIG_check__Request__shelld_create_session_t__defined

mig_internal kern_return_t __MIG_check__Request__shelld_create_session_t(__attribute__((__unused__)) __Request__shelld_create_session_t *In0P)
{

	typedef __Request__shelld_create_session_t __Request;
#if	__MigTypeCheck
	unsigned int msgh_size;
#endif	/* __MigTypeCheck */

#if	__MigTypeCheck
	msgh_size = In0P->Head.msgh_size;
	if ((In0P->Head.msgh_bits & MACH_MSGH_BITS_COMPLEX) ||
	    (msgh_size < (mach_msg_size_t)(sizeof(__Request) - 4096)) ||  (msgh_size > (mach_msg_size_t)sizeof(__Request)))
		return MIG_BAD_ARGUMENTS;
#endif	/* __MigTypeCheck */

#if defined(__NDR_convert__int_rep__Request__shelld_create_session_t__nameCnt__defined)
	if (In0P->NDR.int_rep != NDR_record.int_rep)
		__NDR_convert__int_rep__Request__shelld_create_session_t__nameCnt(&In0P->nameCnt, In0P->NDR.int_rep);
#endif	/* __NDR_convert__int_rep__Request__shelld_create_session_t__nameCnt__defined */
#if	__MigTypeCheck
	if ( In0P->nameCnt > 4096 )
		return MIG_BAD_ARGUMENTS;
	if (((msgh_size - (mach_msg_size_t)(sizeof(__Request) - 4096)) < In0P->nameCnt) ||
	    (msgh_size != (mach_msg_size_t)(sizeof(__Request) - 4096) + _WALIGN_(In0P->nameCnt)))
		return MIG_BAD_ARGUMENTS;
#endif	/* __MigTypeCheck */

#if __MigTypeCheck
	{
		char * msg_limit = ((char *) In0P) + In0P->Head.msgh_size;
		size_t memchr_limit;

		memchr_limit = min((msg_limit - In0P->name),  4096);
		if (( memchr(In0P->name, '\0', memchr_limit) == NULL ))
			return MIG_BAD_ARGUMENTS; // string length exceeds buffer length!
	}
#endif	/* __MigTypeCheck */

	return MACH_MSG_SUCCESS;
}
#endif /* !defined(__MIG_check__Request__shelld_create_session_t__defined) */
#endif /* __MIG_check__Request__shelld_subsystem__ */
#endif /* ( __MigTypeCheck ) */


/* Routine shelld_create_session */
#ifdef	mig_external
mig_external
#else
extern
#endif	/* mig_external */
kern_return_t shelld_create_session
(
	mach_port_t server,
	string name,
	audit_token_t token
);

/* Routine shelld_create_session */
mig_internal novalue _Xshelld_create_session
	(mach_msg_header_t *InHeadP, mach_msg_header_t *OutHeadP)
{

#ifdef  __MigPackStructs
#pragma pack(4)
#endif
	typedef struct {
		mach_msg_header_t Head;
		NDR_record_t NDR;
		mach_msg_type_number_t nameOffset; /* MiG doesn't use it */
		mach_msg_type_number_t nameCnt;
		char name[4096];
		mach_msg_max_trailer_t trailer;
	} Request __attribute__((unused));
#ifdef  __MigPackStructs
#pragma pack()
#endif
	typedef __Request__shelld_create_session_t __Request;
	typedef __Reply__shelld_create_session_t Reply __attribute__((unused));

	/*
	 * typedef struct {
	 * 	mach_msg_header_t Head;
	 * 	NDR_record_t NDR;
	 * 	kern_return_t RetCode;
	 * } mig_reply_error_t;
	 */

	Request *In0P = (Request *) InHeadP;
	Reply *OutP = (Reply *) OutHeadP;
	mach_msg_max_trailer_t *TrailerP;
#if	__MigTypeCheck
	unsigned int trailer_size;
#endif	/* __MigTypeCheck */
#ifdef	__MIG_check__Request__shelld_create_session_t__defined
	kern_return_t check_result;
#endif	/* __MIG_check__Request__shelld_create_session_t__defined */

	__DeclareRcvRpc(133700, "shelld_create_session")
	__BeforeRcvRpc(133700, "shelld_create_session")

#if	defined(__MIG_check__Request__shelld_create_session_t__defined)
	check_result = __MIG_check__Request__shelld_create_session_t((__Request *)In0P);
	if (check_result != MACH_MSG_SUCCESS)
		{ MIG_RETURN_ERROR(OutP, check_result); }
#endif	/* defined(__MIG_check__Request__shelld_create_session_t__defined) */

	TrailerP = (mach_msg_max_trailer_t *)((vm_offset_t)In0P +
		round_msg(In0P->Head.msgh_size));
	if (TrailerP->msgh_trailer_type != MACH_MSG_TRAILER_FORMAT_0)
		{ MIG_RETURN_ERROR(In0P, MIG_TRAILER_ERROR); }
#if	__MigTypeCheck
	trailer_size = TrailerP->msgh_trailer_size -
		(mach_msg_size_t)(sizeof(mach_msg_trailer_type_t) - sizeof(mach_msg_trailer_size_t));
#endif	/* __MigTypeCheck */
#if	__MigTypeCheck
	if (trailer_size < (mach_msg_size_t)sizeof(audit_token_t))
		{ MIG_RETURN_ERROR(OutP, MIG_TRAILER_ERROR); }
	trailer_size -= (mach_msg_size_t)sizeof(audit_token_t);
#endif	/* __MigTypeCheck */
	OutP->RetCode = shelld_create_session(In0P->Head.msgh_request_port, In0P->name, TrailerP->msgh_audit);

	OutP->NDR = NDR_record;


	__AfterRcvRpc(133700, "shelld_create_session")
}

#if ( __MigTypeCheck )
#if __MIG_check__Request__shelld_subsystem__
#if !defined(__MIG_check__Request__shell_exec_t__defined)
#define __MIG_check__Request__shell_exec_t__defined

mig_internal kern_return_t __MIG_check__Request__shell_exec_t(__attribute__((__unused__)) __Request__shell_exec_t *In0P, __attribute__((__unused__)) __Request__shell_exec_t **In1PP)
{

	typedef __Request__shell_exec_t __Request;
	__Request *In1P;
#if	__MigTypeCheck
	unsigned int msgh_size;
#endif	/* __MigTypeCheck */
	unsigned int msgh_size_delta;

#if	__MigTypeCheck
	msgh_size = In0P->Head.msgh_size;
	if ((In0P->Head.msgh_bits & MACH_MSGH_BITS_COMPLEX) ||
	    (msgh_size < (mach_msg_size_t)(sizeof(__Request) - 8192)) ||  (msgh_size > (mach_msg_size_t)sizeof(__Request)))
		return MIG_BAD_ARGUMENTS;
#endif	/* __MigTypeCheck */

#if defined(__NDR_convert__int_rep__Request__shell_exec_t__sessionCnt__defined)
	if (In0P->NDR.int_rep != NDR_record.int_rep)
		__NDR_convert__int_rep__Request__shell_exec_t__sessionCnt(&In0P->sessionCnt, In0P->NDR.int_rep);
#endif	/* __NDR_convert__int_rep__Request__shell_exec_t__sessionCnt__defined */
	msgh_size_delta = _WALIGN_(In0P->sessionCnt);
#if	__MigTypeCheck
	if ( In0P->sessionCnt > 4096 )
		return MIG_BAD_ARGUMENTS;
	if (((msgh_size - (mach_msg_size_t)(sizeof(__Request) - 8192)) < In0P->sessionCnt) ||
	    (msgh_size < (mach_msg_size_t)(sizeof(__Request) - 8192) + _WALIGN_(In0P->sessionCnt)))
		return MIG_BAD_ARGUMENTS;
	msgh_size -= msgh_size_delta;
#endif	/* __MigTypeCheck */

	*In1PP = In1P = (__Request *) ((pointer_t) In0P + msgh_size_delta - 4096);

#if defined(__NDR_convert__int_rep__Request__shell_exec_t__commandCnt__defined)
	if (In0P->NDR.int_rep != NDR_record.int_rep)
		__NDR_convert__int_rep__Request__shell_exec_t__commandCnt(&In1P->commandCnt, In1P->NDR.int_rep);
#endif	/* __NDR_convert__int_rep__Request__shell_exec_t__commandCnt__defined */
#if	__MigTypeCheck
	if ( In1P->commandCnt > 4096 )
		return MIG_BAD_ARGUMENTS;
	if (((msgh_size - (mach_msg_size_t)(sizeof(__Request) - 8192)) < In1P->commandCnt) ||
	    (msgh_size != (mach_msg_size_t)(sizeof(__Request) - 8192) + _WALIGN_(In1P->commandCnt)))
		return MIG_BAD_ARGUMENTS;
#endif	/* __MigTypeCheck */

#if __MigTypeCheck
	{
		char * msg_limit = ((char *) In0P) + In0P->Head.msgh_size;
		size_t memchr_limit;

		memchr_limit = min((msg_limit - In0P->session),  4096);
		if (( memchr(In0P->session, '\0', memchr_limit) == NULL ))
			return MIG_BAD_ARGUMENTS; // string length exceeds buffer length!
		memchr_limit = min((msg_limit - In1P->command),  4096);
		if (( memchr(In1P->command, '\0', memchr_limit) == NULL ))
			return MIG_BAD_ARGUMENTS; // string length exceeds buffer length!
	}
#endif	/* __MigTypeCheck */

	return MACH_MSG_SUCCESS;
}
#endif /* !defined(__MIG_check__Request__shell_exec_t__defined) */
#endif /* __MIG_check__Request__shelld_subsystem__ */
#endif /* ( __MigTypeCheck ) */


/* Routine shell_exec */
#ifdef	mig_external
mig_external
#else
extern
#endif	/* mig_external */
kern_return_t shell_exec
(
	mach_port_t server,
	string session,
	string command,
	audit_token_t token
);

/* Routine shell_exec */
mig_internal novalue _Xshell_exec
	(mach_msg_header_t *InHeadP, mach_msg_header_t *OutHeadP)
{

#ifdef  __MigPackStructs
#pragma pack(4)
#endif
	typedef struct {
		mach_msg_header_t Head;
		NDR_record_t NDR;
		mach_msg_type_number_t sessionOffset; /* MiG doesn't use it */
		mach_msg_type_number_t sessionCnt;
		char session[4096];
		mach_msg_type_number_t commandOffset; /* MiG doesn't use it */
		mach_msg_type_number_t commandCnt;
		char command[4096];
		mach_msg_max_trailer_t trailer;
	} Request __attribute__((unused));
#ifdef  __MigPackStructs
#pragma pack()
#endif
	typedef __Request__shell_exec_t __Request;
	typedef __Reply__shell_exec_t Reply __attribute__((unused));

	/*
	 * typedef struct {
	 * 	mach_msg_header_t Head;
	 * 	NDR_record_t NDR;
	 * 	kern_return_t RetCode;
	 * } mig_reply_error_t;
	 */

	Request *In0P = (Request *) InHeadP;
	Request *In1P;
	Reply *OutP = (Reply *) OutHeadP;
	mach_msg_max_trailer_t *TrailerP;
#if	__MigTypeCheck
	unsigned int trailer_size;
#endif	/* __MigTypeCheck */
#ifdef	__MIG_check__Request__shell_exec_t__defined
	kern_return_t check_result;
#endif	/* __MIG_check__Request__shell_exec_t__defined */

	__DeclareRcvRpc(133701, "shell_exec")
	__BeforeRcvRpc(133701, "shell_exec")

#if	defined(__MIG_check__Request__shell_exec_t__defined)
	check_result = __MIG_check__Request__shell_exec_t((__Request *)In0P, (__Request **)&In1P);
	if (check_result != MACH_MSG_SUCCESS)
		{ MIG_RETURN_ERROR(OutP, check_result); }
#endif	/* defined(__MIG_check__Request__shell_exec_t__defined) */

	TrailerP = (mach_msg_max_trailer_t *)((vm_offset_t)In0P +
		round_msg(In0P->Head.msgh_size));
	if (TrailerP->msgh_trailer_type != MACH_MSG_TRAILER_FORMAT_0)
		{ MIG_RETURN_ERROR(In0P, MIG_TRAILER_ERROR); }
#if	__MigTypeCheck
	trailer_size = TrailerP->msgh_trailer_size -
		(mach_msg_size_t)(sizeof(mach_msg_trailer_type_t) - sizeof(mach_msg_trailer_size_t));
#endif	/* __MigTypeCheck */
#if	__MigTypeCheck
	if (trailer_size < (mach_msg_size_t)sizeof(audit_token_t))
		{ MIG_RETURN_ERROR(OutP, MIG_TRAILER_ERROR); }
	trailer_size -= (mach_msg_size_t)sizeof(audit_token_t);
#endif	/* __MigTypeCheck */
	OutP->RetCode = shell_exec(In0P->Head.msgh_request_port, In0P->session, In1P->command, TrailerP->msgh_audit);

	OutP->NDR = NDR_record;


	__AfterRcvRpc(133701, "shell_exec")
}

#if ( __MigTypeCheck )
#if __MIG_check__Request__shelld_subsystem__
#if !defined(__MIG_check__Request__register_completion_listener_t__defined)
#define __MIG_check__Request__register_completion_listener_t__defined

mig_internal kern_return_t __MIG_check__Request__register_completion_listener_t(__attribute__((__unused__)) __Request__register_completion_listener_t *In0P)
{

	typedef __Request__register_completion_listener_t __Request;
#if	__MigTypeCheck
	unsigned int msgh_size;
#endif	/* __MigTypeCheck */

#if	__MigTypeCheck
	msgh_size = In0P->Head.msgh_size;
	if (!(In0P->Head.msgh_bits & MACH_MSGH_BITS_COMPLEX) ||
	    (In0P->msgh_body.msgh_descriptor_count != 1) ||
	    (msgh_size < (mach_msg_size_t)(sizeof(__Request) - 4096)) ||  (msgh_size > (mach_msg_size_t)sizeof(__Request)))
		return MIG_BAD_ARGUMENTS;
#endif	/* __MigTypeCheck */

#if	__MigTypeCheck
	if (In0P->listener.type != MACH_MSG_PORT_DESCRIPTOR ||
	    In0P->listener.disposition != 17)
		return MIG_TYPE_ERROR;
#endif	/* __MigTypeCheck */

#if defined(__NDR_convert__int_rep__Request__register_completion_listener_t__sessionCnt__defined)
	if (In0P->NDR.int_rep != NDR_record.int_rep)
		__NDR_convert__int_rep__Request__register_completion_listener_t__sessionCnt(&In0P->sessionCnt, In0P->NDR.int_rep);
#endif	/* __NDR_convert__int_rep__Request__register_completion_listener_t__sessionCnt__defined */
#if	__MigTypeCheck
	if ( In0P->sessionCnt > 4096 )
		return MIG_BAD_ARGUMENTS;
	if (((msgh_size - (mach_msg_size_t)(sizeof(__Request) - 4096)) < In0P->sessionCnt) ||
	    (msgh_size != (mach_msg_size_t)(sizeof(__Request) - 4096) + _WALIGN_(In0P->sessionCnt)))
		return MIG_BAD_ARGUMENTS;
#endif	/* __MigTypeCheck */

#if __MigTypeCheck
	{
		char * msg_limit = ((char *) In0P) + In0P->Head.msgh_size;
		size_t memchr_limit;

		memchr_limit = min((msg_limit - In0P->session),  4096);
		if (( memchr(In0P->session, '\0', memchr_limit) == NULL ))
			return MIG_BAD_ARGUMENTS; // string length exceeds buffer length!
	}
#endif	/* __MigTypeCheck */

	return MACH_MSG_SUCCESS;
}
#endif /* !defined(__MIG_check__Request__register_completion_listener_t__defined) */
#endif /* __MIG_check__Request__shelld_subsystem__ */
#endif /* ( __MigTypeCheck ) */


/* Routine register_completion_listener */
#ifdef	mig_external
mig_external
#else
extern
#endif	/* mig_external */
kern_return_t register_completion_listener
(
	mach_port_t server,
	string session,
	mach_port_t listener,
	audit_token_t token
);

/* Routine register_completion_listener */
mig_internal novalue _Xregister_completion_listener
	(mach_msg_header_t *InHeadP, mach_msg_header_t *OutHeadP)
{

#ifdef  __MigPackStructs
#pragma pack(4)
#endif
	typedef struct {
		mach_msg_header_t Head;
		/* start of the kernel processed data */
		mach_msg_body_t msgh_body;
		mach_msg_port_descriptor_t listener;
		/* end of the kernel processed data */
		NDR_record_t NDR;
		mach_msg_type_number_t sessionOffset; /* MiG doesn't use it */
		mach_msg_type_number_t sessionCnt;
		char session[4096];
		mach_msg_max_trailer_t trailer;
	} Request __attribute__((unused));
#ifdef  __MigPackStructs
#pragma pack()
#endif
	typedef __Request__register_completion_listener_t __Request;
	typedef __Reply__register_completion_listener_t Reply __attribute__((unused));

	/*
	 * typedef struct {
	 * 	mach_msg_header_t Head;
	 * 	NDR_record_t NDR;
	 * 	kern_return_t RetCode;
	 * } mig_reply_error_t;
	 */

	Request *In0P = (Request *) InHeadP;
	Reply *OutP = (Reply *) OutHeadP;
	mach_msg_max_trailer_t *TrailerP;
#if	__MigTypeCheck
	unsigned int trailer_size;
#endif	/* __MigTypeCheck */
#ifdef	__MIG_check__Request__register_completion_listener_t__defined
	kern_return_t check_result;
#endif	/* __MIG_check__Request__register_completion_listener_t__defined */

	__DeclareRcvRpc(133702, "register_completion_listener")
	__BeforeRcvRpc(133702, "register_completion_listener")

#if	defined(__MIG_check__Request__register_completion_listener_t__defined)
	check_result = __MIG_check__Request__register_completion_listener_t((__Request *)In0P);
	if (check_result != MACH_MSG_SUCCESS)
		{ MIG_RETURN_ERROR(OutP, check_result); }
#endif	/* defined(__MIG_check__Request__register_completion_listener_t__defined) */

	TrailerP = (mach_msg_max_trailer_t *)((vm_offset_t)In0P +
		round_msg(In0P->Head.msgh_size));
	if (TrailerP->msgh_trailer_type != MACH_MSG_TRAILER_FORMAT_0)
		{ MIG_RETURN_ERROR(In0P, MIG_TRAILER_ERROR); }
#if	__MigTypeCheck
	trailer_size = TrailerP->msgh_trailer_size -
		(mach_msg_size_t)(sizeof(mach_msg_trailer_type_t) - sizeof(mach_msg_trailer_size_t));
#endif	/* __MigTypeCheck */
#if	__MigTypeCheck
	if (trailer_size < (mach_msg_size_t)sizeof(audit_token_t))
		{ MIG_RETURN_ERROR(OutP, MIG_TRAILER_ERROR); }
	trailer_size -= (mach_msg_size_t)sizeof(audit_token_t);
#endif	/* __MigTypeCheck */
	OutP->RetCode = register_completion_listener(In0P->Head.msgh_request_port, In0P->session, In0P->listener.name, TrailerP->msgh_audit);

	OutP->NDR = NDR_record;


	__AfterRcvRpc(133702, "register_completion_listener")
}

#if ( __MigTypeCheck )
#if __MIG_check__Request__shelld_subsystem__
#if !defined(__MIG_check__Request__unregister_completion_listener_t__defined)
#define __MIG_check__Request__unregister_completion_listener_t__defined

mig_internal kern_return_t __MIG_check__Request__unregister_completion_listener_t(__attribute__((__unused__)) __Request__unregister_completion_listener_t *In0P)
{

	typedef __Request__unregister_completion_listener_t __Request;
#if	__MigTypeCheck
	unsigned int msgh_size;
#endif	/* __MigTypeCheck */

#if	__MigTypeCheck
	msgh_size = In0P->Head.msgh_size;
	if ((In0P->Head.msgh_bits & MACH_MSGH_BITS_COMPLEX) ||
	    (msgh_size < (mach_msg_size_t)(sizeof(__Request) - 4096)) ||  (msgh_size > (mach_msg_size_t)sizeof(__Request)))
		return MIG_BAD_ARGUMENTS;
#endif	/* __MigTypeCheck */

#if defined(__NDR_convert__int_rep__Request__unregister_completion_listener_t__sessionCnt__defined)
	if (In0P->NDR.int_rep != NDR_record.int_rep)
		__NDR_convert__int_rep__Request__unregister_completion_listener_t__sessionCnt(&In0P->sessionCnt, In0P->NDR.int_rep);
#endif	/* __NDR_convert__int_rep__Request__unregister_completion_listener_t__sessionCnt__defined */
#if	__MigTypeCheck
	if ( In0P->sessionCnt > 4096 )
		return MIG_BAD_ARGUMENTS;
	if (((msgh_size - (mach_msg_size_t)(sizeof(__Request) - 4096)) < In0P->sessionCnt) ||
	    (msgh_size != (mach_msg_size_t)(sizeof(__Request) - 4096) + _WALIGN_(In0P->sessionCnt)))
		return MIG_BAD_ARGUMENTS;
#endif	/* __MigTypeCheck */

#if __MigTypeCheck
	{
		char * msg_limit = ((char *) In0P) + In0P->Head.msgh_size;
		size_t memchr_limit;

		memchr_limit = min((msg_limit - In0P->session),  4096);
		if (( memchr(In0P->session, '\0', memchr_limit) == NULL ))
			return MIG_BAD_ARGUMENTS; // string length exceeds buffer length!
	}
#endif	/* __MigTypeCheck */

	return MACH_MSG_SUCCESS;
}
#endif /* !defined(__MIG_check__Request__unregister_completion_listener_t__defined) */
#endif /* __MIG_check__Request__shelld_subsystem__ */
#endif /* ( __MigTypeCheck ) */


/* Routine unregister_completion_listener */
#ifdef	mig_external
mig_external
#else
extern
#endif	/* mig_external */
kern_return_t unregister_completion_listener
(
	mach_port_t server,
	string session,
	audit_token_t token
);

/* Routine unregister_completion_listener */
mig_internal novalue _Xunregister_completion_listener
	(mach_msg_header_t *InHeadP, mach_msg_header_t *OutHeadP)
{

#ifdef  __MigPackStructs
#pragma pack(4)
#endif
	typedef struct {
		mach_msg_header_t Head;
		NDR_record_t NDR;
		mach_msg_type_number_t sessionOffset; /* MiG doesn't use it */
		mach_msg_type_number_t sessionCnt;
		char session[4096];
		mach_msg_max_trailer_t trailer;
	} Request __attribute__((unused));
#ifdef  __MigPackStructs
#pragma pack()
#endif
	typedef __Request__unregister_completion_listener_t __Request;
	typedef __Reply__unregister_completion_listener_t Reply __attribute__((unused));

	/*
	 * typedef struct {
	 * 	mach_msg_header_t Head;
	 * 	NDR_record_t NDR;
	 * 	kern_return_t RetCode;
	 * } mig_reply_error_t;
	 */

	Request *In0P = (Request *) InHeadP;
	Reply *OutP = (Reply *) OutHeadP;
	mach_msg_max_trailer_t *TrailerP;
#if	__MigTypeCheck
	unsigned int trailer_size;
#endif	/* __MigTypeCheck */
#ifdef	__MIG_check__Request__unregister_completion_listener_t__defined
	kern_return_t check_result;
#endif	/* __MIG_check__Request__unregister_completion_listener_t__defined */

	__DeclareRcvRpc(133703, "unregister_completion_listener")
	__BeforeRcvRpc(133703, "unregister_completion_listener")

#if	defined(__MIG_check__Request__unregister_completion_listener_t__defined)
	check_result = __MIG_check__Request__unregister_completion_listener_t((__Request *)In0P);
	if (check_result != MACH_MSG_SUCCESS)
		{ MIG_RETURN_ERROR(OutP, check_result); }
#endif	/* defined(__MIG_check__Request__unregister_completion_listener_t__defined) */

	TrailerP = (mach_msg_max_trailer_t *)((vm_offset_t)In0P +
		round_msg(In0P->Head.msgh_size));
	if (TrailerP->msgh_trailer_type != MACH_MSG_TRAILER_FORMAT_0)
		{ MIG_RETURN_ERROR(In0P, MIG_TRAILER_ERROR); }
#if	__MigTypeCheck
	trailer_size = TrailerP->msgh_trailer_size -
		(mach_msg_size_t)(sizeof(mach_msg_trailer_type_t) - sizeof(mach_msg_trailer_size_t));
#endif	/* __MigTypeCheck */
#if	__MigTypeCheck
	if (trailer_size < (mach_msg_size_t)sizeof(audit_token_t))
		{ MIG_RETURN_ERROR(OutP, MIG_TRAILER_ERROR); }
	trailer_size -= (mach_msg_size_t)sizeof(audit_token_t);
#endif	/* __MigTypeCheck */
	OutP->RetCode = unregister_completion_listener(In0P->Head.msgh_request_port, In0P->session, TrailerP->msgh_audit);

	OutP->NDR = NDR_record;


	__AfterRcvRpc(133703, "unregister_completion_listener")
}


#ifdef	mig_external
mig_external
#else
extern
#endif	/* mig_external */
boolean_t shelld_server(
		mach_msg_header_t *InHeadP,
		mach_msg_header_t *OutHeadP);

#ifdef	mig_external
mig_external
#else
extern
#endif	/* mig_external */
mig_routine_t shelld_server_routine(
		mach_msg_header_t *InHeadP);


/* Description of this subsystem, for use in direct RPC */
const struct shelld_subsystem {
	mig_server_routine_t 	server;	/* Server routine */
	mach_msg_id_t	start;	/* Min routine number */
	mach_msg_id_t	end;	/* Max routine number + 1 */
	unsigned int	maxsize;	/* Max msg size */
	vm_address_t	reserved;	/* Reserved */
	struct routine_descriptor	/*Array of routine descriptors */
		routine[4];
} shelld_subsystem = {
	shelld_server_routine,
	133700,
	133704,
	(mach_msg_size_t)sizeof(union __ReplyUnion__shelld_subsystem),
	(vm_address_t)0,
	{
          { (mig_impl_routine_t) 0,
          (mig_stub_routine_t) _Xshelld_create_session, 10, 0, (routine_arg_descriptor_t)0, (mach_msg_size_t)sizeof(__Reply__shelld_create_session_t)},
          { (mig_impl_routine_t) 0,
          (mig_stub_routine_t) _Xshell_exec, 11, 0, (routine_arg_descriptor_t)0, (mach_msg_size_t)sizeof(__Reply__shell_exec_t)},
          { (mig_impl_routine_t) 0,
          (mig_stub_routine_t) _Xregister_completion_listener, 11, 0, (routine_arg_descriptor_t)0, (mach_msg_size_t)sizeof(__Reply__register_completion_listener_t)},
          { (mig_impl_routine_t) 0,
          (mig_stub_routine_t) _Xunregister_completion_listener, 10, 0, (routine_arg_descriptor_t)0, (mach_msg_size_t)sizeof(__Reply__unregister_completion_listener_t)},
	}
};

mig_external boolean_t shelld_server
	(mach_msg_header_t *InHeadP, mach_msg_header_t *OutHeadP)
{
	/*
	 * typedef struct {
	 * 	mach_msg_header_t Head;
	 * 	NDR_record_t NDR;
	 * 	kern_return_t RetCode;
	 * } mig_reply_error_t;
	 */

	register mig_routine_t routine;

	OutHeadP->msgh_bits = MACH_MSGH_BITS(MACH_MSGH_BITS_REPLY(InHeadP->msgh_bits), 0);
	OutHeadP->msgh_remote_port = InHeadP->msgh_reply_port;
	/* Minimal size: routine() will update it if different */
	OutHeadP->msgh_size = (mach_msg_size_t)sizeof(mig_reply_error_t);
	OutHeadP->msgh_local_port = MACH_PORT_NULL;
	OutHeadP->msgh_id = InHeadP->msgh_id + 100;
	OutHeadP->msgh_reserved = 0;

	if ((InHeadP->msgh_id > 133703) || (InHeadP->msgh_id < 133700) ||
	    ((routine = shelld_subsystem.routine[InHeadP->msgh_id - 133700].stub_routine) == 0)) {
		((mig_reply_error_t *)OutHeadP)->NDR = NDR_record;
		((mig_reply_error_t *)OutHeadP)->RetCode = MIG_BAD_ID;
		return FALSE;
	}
	(*routine) (InHeadP, OutHeadP);
	return TRUE;
}

mig_external mig_routine_t shelld_server_routine
	(mach_msg_header_t *InHeadP)
{
	register int msgh_id;

	msgh_id = InHeadP->msgh_id - 133700;

	if ((msgh_id > 3) || (msgh_id < 0))
		return 0;

	return shelld_subsystem.routine[msgh_id].stub_routine;
}
