/*
 * IDENTIFICATION:
 * stub generated Thu Dec 13 19:13:57 2018
 * with a MiG generated by bootstrap_cmds-96.20.2.200.4
 * OPTIONS: 
 */
#define	__MIG_check__Reply__shelld_subsystem__ 1

#include "shelld.h"


#ifndef	mig_internal
#define	mig_internal	static __inline__
#endif	/* mig_internal */

#ifndef	mig_external
#define mig_external
#endif	/* mig_external */

#if	!defined(__MigTypeCheck) && defined(TypeCheck)
#define	__MigTypeCheck		TypeCheck	/* Legacy setting */
#endif	/* !defined(__MigTypeCheck) */

#if	!defined(__MigKernelSpecificCode) && defined(_MIG_KERNEL_SPECIFIC_CODE_)
#define	__MigKernelSpecificCode	_MIG_KERNEL_SPECIFIC_CODE_	/* Legacy setting */
#endif	/* !defined(__MigKernelSpecificCode) */

#ifndef	LimitCheck
#define	LimitCheck 0
#endif	/* LimitCheck */

#ifndef	min
#define	min(a,b)  ( ((a) < (b))? (a): (b) )
#endif	/* min */

#if !defined(_WALIGN_)
#define _WALIGN_(x) (((x) + 3) & ~3)
#endif /* !defined(_WALIGN_) */

#if !defined(_WALIGNSZ_)
#define _WALIGNSZ_(x) _WALIGN_(sizeof(x))
#endif /* !defined(_WALIGNSZ_) */

#ifndef	UseStaticTemplates
#define	UseStaticTemplates	0
#endif	/* UseStaticTemplates */

#ifndef	__MachMsgErrorWithTimeout
#define	__MachMsgErrorWithTimeout(_R_) { \
	switch (_R_) { \
	case MACH_SEND_INVALID_DATA: \
	case MACH_SEND_INVALID_DEST: \
	case MACH_SEND_INVALID_HEADER: \
		mig_put_reply_port(InP->Head.msgh_reply_port); \
		break; \
	case MACH_SEND_TIMED_OUT: \
	case MACH_RCV_TIMED_OUT: \
	default: \
		mig_dealloc_reply_port(InP->Head.msgh_reply_port); \
	} \
}
#endif	/* __MachMsgErrorWithTimeout */

#ifndef	__MachMsgErrorWithoutTimeout
#define	__MachMsgErrorWithoutTimeout(_R_) { \
	switch (_R_) { \
	case MACH_SEND_INVALID_DATA: \
	case MACH_SEND_INVALID_DEST: \
	case MACH_SEND_INVALID_HEADER: \
		mig_put_reply_port(InP->Head.msgh_reply_port); \
		break; \
	default: \
		mig_dealloc_reply_port(InP->Head.msgh_reply_port); \
	} \
}
#endif	/* __MachMsgErrorWithoutTimeout */

#ifndef	__DeclareSendRpc
#define	__DeclareSendRpc(_NUM_, _NAME_)
#endif	/* __DeclareSendRpc */

#ifndef	__BeforeSendRpc
#define	__BeforeSendRpc(_NUM_, _NAME_)
#endif	/* __BeforeSendRpc */

#ifndef	__AfterSendRpc
#define	__AfterSendRpc(_NUM_, _NAME_)
#endif	/* __AfterSendRpc */

#ifndef	__DeclareSendSimple
#define	__DeclareSendSimple(_NUM_, _NAME_)
#endif	/* __DeclareSendSimple */

#ifndef	__BeforeSendSimple
#define	__BeforeSendSimple(_NUM_, _NAME_)
#endif	/* __BeforeSendSimple */

#ifndef	__AfterSendSimple
#define	__AfterSendSimple(_NUM_, _NAME_)
#endif	/* __AfterSendSimple */

#define msgh_request_port	msgh_remote_port
#define msgh_reply_port		msgh_local_port



#if ( __MigTypeCheck )
#if __MIG_check__Reply__shelld_subsystem__
#if !defined(__MIG_check__Reply__shelld_create_session_t__defined)
#define __MIG_check__Reply__shelld_create_session_t__defined

mig_internal kern_return_t __MIG_check__Reply__shelld_create_session_t(__Reply__shelld_create_session_t *Out0P)
{

	typedef __Reply__shelld_create_session_t __Reply __attribute__((unused));
	if (Out0P->Head.msgh_id != 133800) {
	    if (Out0P->Head.msgh_id == MACH_NOTIFY_SEND_ONCE)
		{ return MIG_SERVER_DIED; }
	    else
		{ return MIG_REPLY_MISMATCH; }
	}

#if	__MigTypeCheck
	if ((Out0P->Head.msgh_bits & MACH_MSGH_BITS_COMPLEX) ||
	    (Out0P->Head.msgh_size != (mach_msg_size_t)sizeof(__Reply)))
		{ return MIG_TYPE_ERROR ; }
#endif	/* __MigTypeCheck */

	{
		return Out0P->RetCode;
	}
}
#endif /* !defined(__MIG_check__Reply__shelld_create_session_t__defined) */
#endif /* __MIG_check__Reply__shelld_subsystem__ */
#endif /* ( __MigTypeCheck ) */


/* Routine shelld_create_session */
mig_external kern_return_t shelld_create_session
(
	mach_port_t server,
	string name
)
{

#ifdef  __MigPackStructs
#pragma pack(4)
#endif
	typedef struct {
		mach_msg_header_t Head;
		NDR_record_t NDR;
		mach_msg_type_number_t nameOffset; /* MiG doesn't use it */
		mach_msg_type_number_t nameCnt;
		char name[4096];
	} Request __attribute__((unused));
#ifdef  __MigPackStructs
#pragma pack()
#endif

#ifdef  __MigPackStructs
#pragma pack(4)
#endif
	typedef struct {
		mach_msg_header_t Head;
		NDR_record_t NDR;
		kern_return_t RetCode;
		mach_msg_trailer_t trailer;
	} Reply __attribute__((unused));
#ifdef  __MigPackStructs
#pragma pack()
#endif

#ifdef  __MigPackStructs
#pragma pack(4)
#endif
	typedef struct {
		mach_msg_header_t Head;
		NDR_record_t NDR;
		kern_return_t RetCode;
	} __Reply __attribute__((unused));
#ifdef  __MigPackStructs
#pragma pack()
#endif
	/*
	 * typedef struct {
	 * 	mach_msg_header_t Head;
	 * 	NDR_record_t NDR;
	 * 	kern_return_t RetCode;
	 * } mig_reply_error_t;
	 */

	union {
		Request In;
		Reply Out;
	} Mess;

	Request *InP = &Mess.In;
	Reply *Out0P = &Mess.Out;

	mach_msg_return_t msg_result;
	unsigned int msgh_size;

#ifdef	__MIG_check__Reply__shelld_create_session_t__defined
	kern_return_t check_result;
#endif	/* __MIG_check__Reply__shelld_create_session_t__defined */

	__DeclareSendRpc(133700, "shelld_create_session")

	InP->NDR = NDR_record;

#ifdef USING_MIG_STRNCPY_ZEROFILL
	if (mig_strncpy_zerofill != NULL) {
		InP->nameCnt = mig_strncpy_zerofill(InP->name, name, 4096);
	} else {
#endif /* USING_MIG_STRNCPY_ZEROFILL */
		InP->nameCnt = mig_strncpy(InP->name, name, 4096);
#ifdef USING_MIG_STRNCPY_ZEROFILL
	}
#endif /* USING_MIG_STRNCPY_ZEROFILL */

	msgh_size = (mach_msg_size_t)(sizeof(Request) - 4096) + (_WALIGN_(InP->nameCnt));
	InP->Head.msgh_bits =
		MACH_MSGH_BITS(19, MACH_MSG_TYPE_MAKE_SEND_ONCE);
	/* msgh_size passed as argument */
	InP->Head.msgh_request_port = server;
	InP->Head.msgh_reply_port = mig_get_reply_port();
	InP->Head.msgh_id = 133700;
	InP->Head.msgh_reserved = 0;
	
/* BEGIN VOUCHER CODE */

#ifdef USING_VOUCHERS
	if (voucher_mach_msg_set != NULL) {
		voucher_mach_msg_set(&InP->Head);
	}
#endif // USING_VOUCHERS
	
/* END VOUCHER CODE */

	__BeforeSendRpc(133700, "shelld_create_session")
	msg_result = mach_msg(&InP->Head, MACH_SEND_MSG|MACH_RCV_MSG|MACH_MSG_OPTION_NONE, msgh_size, (mach_msg_size_t)sizeof(Reply), InP->Head.msgh_reply_port, MACH_MSG_TIMEOUT_NONE, MACH_PORT_NULL);
	__AfterSendRpc(133700, "shelld_create_session")
	if (msg_result != MACH_MSG_SUCCESS) {
		__MachMsgErrorWithoutTimeout(msg_result);
		{ return msg_result; }
	}


#if	defined(__MIG_check__Reply__shelld_create_session_t__defined)
	check_result = __MIG_check__Reply__shelld_create_session_t((__Reply__shelld_create_session_t *)Out0P);
	if (check_result != MACH_MSG_SUCCESS)
		{ return check_result; }
#endif	/* defined(__MIG_check__Reply__shelld_create_session_t__defined) */

	return KERN_SUCCESS;
}

#if ( __MigTypeCheck )
#if __MIG_check__Reply__shelld_subsystem__
#if !defined(__MIG_check__Reply__shell_exec_t__defined)
#define __MIG_check__Reply__shell_exec_t__defined

mig_internal kern_return_t __MIG_check__Reply__shell_exec_t(__Reply__shell_exec_t *Out0P)
{

	typedef __Reply__shell_exec_t __Reply __attribute__((unused));
	if (Out0P->Head.msgh_id != 133801) {
	    if (Out0P->Head.msgh_id == MACH_NOTIFY_SEND_ONCE)
		{ return MIG_SERVER_DIED; }
	    else
		{ return MIG_REPLY_MISMATCH; }
	}

#if	__MigTypeCheck
	if ((Out0P->Head.msgh_bits & MACH_MSGH_BITS_COMPLEX) ||
	    (Out0P->Head.msgh_size != (mach_msg_size_t)sizeof(__Reply)))
		{ return MIG_TYPE_ERROR ; }
#endif	/* __MigTypeCheck */

	{
		return Out0P->RetCode;
	}
}
#endif /* !defined(__MIG_check__Reply__shell_exec_t__defined) */
#endif /* __MIG_check__Reply__shelld_subsystem__ */
#endif /* ( __MigTypeCheck ) */


/* Routine shell_exec */
mig_external kern_return_t shell_exec
(
	mach_port_t server,
	string session,
	string command
)
{

#ifdef  __MigPackStructs
#pragma pack(4)
#endif
	typedef struct {
		mach_msg_header_t Head;
		NDR_record_t NDR;
		mach_msg_type_number_t sessionOffset; /* MiG doesn't use it */
		mach_msg_type_number_t sessionCnt;
		char session[4096];
		mach_msg_type_number_t commandOffset; /* MiG doesn't use it */
		mach_msg_type_number_t commandCnt;
		char command[4096];
	} Request __attribute__((unused));
#ifdef  __MigPackStructs
#pragma pack()
#endif

#ifdef  __MigPackStructs
#pragma pack(4)
#endif
	typedef struct {
		mach_msg_header_t Head;
		NDR_record_t NDR;
		kern_return_t RetCode;
		mach_msg_trailer_t trailer;
	} Reply __attribute__((unused));
#ifdef  __MigPackStructs
#pragma pack()
#endif

#ifdef  __MigPackStructs
#pragma pack(4)
#endif
	typedef struct {
		mach_msg_header_t Head;
		NDR_record_t NDR;
		kern_return_t RetCode;
	} __Reply __attribute__((unused));
#ifdef  __MigPackStructs
#pragma pack()
#endif
	/*
	 * typedef struct {
	 * 	mach_msg_header_t Head;
	 * 	NDR_record_t NDR;
	 * 	kern_return_t RetCode;
	 * } mig_reply_error_t;
	 */

	union {
		Request In;
		Reply Out;
	} Mess;

	Request *InP = &Mess.In;
	Reply *Out0P = &Mess.Out;

	mach_msg_return_t msg_result;
	unsigned int msgh_size;
	unsigned int msgh_size_delta;


#ifdef	__MIG_check__Reply__shell_exec_t__defined
	kern_return_t check_result;
#endif	/* __MIG_check__Reply__shell_exec_t__defined */

	__DeclareSendRpc(133701, "shell_exec")

	InP->NDR = NDR_record;

#ifdef USING_MIG_STRNCPY_ZEROFILL
	if (mig_strncpy_zerofill != NULL) {
		InP->sessionCnt = mig_strncpy_zerofill(InP->session, session, 4096);
	} else {
#endif /* USING_MIG_STRNCPY_ZEROFILL */
		InP->sessionCnt = mig_strncpy(InP->session, session, 4096);
#ifdef USING_MIG_STRNCPY_ZEROFILL
	}
#endif /* USING_MIG_STRNCPY_ZEROFILL */

	msgh_size_delta = _WALIGN_(InP->sessionCnt);
	msgh_size = (mach_msg_size_t)(sizeof(Request) - 8192) + msgh_size_delta;
	InP = (Request *) ((pointer_t) InP + msgh_size_delta - 4096);

#ifdef USING_MIG_STRNCPY_ZEROFILL
	if (mig_strncpy_zerofill != NULL) {
		InP->commandCnt = mig_strncpy_zerofill(InP->command, command, 4096);
	} else {
#endif /* USING_MIG_STRNCPY_ZEROFILL */
		InP->commandCnt = mig_strncpy(InP->command, command, 4096);
#ifdef USING_MIG_STRNCPY_ZEROFILL
	}
#endif /* USING_MIG_STRNCPY_ZEROFILL */

	msgh_size += _WALIGN_(InP->commandCnt);
	InP = &Mess.In;
	InP->Head.msgh_bits =
		MACH_MSGH_BITS(19, MACH_MSG_TYPE_MAKE_SEND_ONCE);
	/* msgh_size passed as argument */
	InP->Head.msgh_request_port = server;
	InP->Head.msgh_reply_port = mig_get_reply_port();
	InP->Head.msgh_id = 133701;
	InP->Head.msgh_reserved = 0;
	
/* BEGIN VOUCHER CODE */

#ifdef USING_VOUCHERS
	if (voucher_mach_msg_set != NULL) {
		voucher_mach_msg_set(&InP->Head);
	}
#endif // USING_VOUCHERS
	
/* END VOUCHER CODE */

	__BeforeSendRpc(133701, "shell_exec")
	msg_result = mach_msg(&InP->Head, MACH_SEND_MSG|MACH_RCV_MSG|MACH_MSG_OPTION_NONE, msgh_size, (mach_msg_size_t)sizeof(Reply), InP->Head.msgh_reply_port, MACH_MSG_TIMEOUT_NONE, MACH_PORT_NULL);
	__AfterSendRpc(133701, "shell_exec")
	if (msg_result != MACH_MSG_SUCCESS) {
		__MachMsgErrorWithoutTimeout(msg_result);
		{ return msg_result; }
	}


#if	defined(__MIG_check__Reply__shell_exec_t__defined)
	check_result = __MIG_check__Reply__shell_exec_t((__Reply__shell_exec_t *)Out0P);
	if (check_result != MACH_MSG_SUCCESS)
		{ return check_result; }
#endif	/* defined(__MIG_check__Reply__shell_exec_t__defined) */

	return KERN_SUCCESS;
}

#if ( __MigTypeCheck )
#if __MIG_check__Reply__shelld_subsystem__
#if !defined(__MIG_check__Reply__register_completion_listener_t__defined)
#define __MIG_check__Reply__register_completion_listener_t__defined

mig_internal kern_return_t __MIG_check__Reply__register_completion_listener_t(__Reply__register_completion_listener_t *Out0P)
{

	typedef __Reply__register_completion_listener_t __Reply __attribute__((unused));
	if (Out0P->Head.msgh_id != 133802) {
	    if (Out0P->Head.msgh_id == MACH_NOTIFY_SEND_ONCE)
		{ return MIG_SERVER_DIED; }
	    else
		{ return MIG_REPLY_MISMATCH; }
	}

#if	__MigTypeCheck
	if ((Out0P->Head.msgh_bits & MACH_MSGH_BITS_COMPLEX) ||
	    (Out0P->Head.msgh_size != (mach_msg_size_t)sizeof(__Reply)))
		{ return MIG_TYPE_ERROR ; }
#endif	/* __MigTypeCheck */

	{
		return Out0P->RetCode;
	}
}
#endif /* !defined(__MIG_check__Reply__register_completion_listener_t__defined) */
#endif /* __MIG_check__Reply__shelld_subsystem__ */
#endif /* ( __MigTypeCheck ) */


/* Routine register_completion_listener */
mig_external kern_return_t register_completion_listener
(
	mach_port_t server,
	string session,
	mach_port_t listener
)
{

#ifdef  __MigPackStructs
#pragma pack(4)
#endif
	typedef struct {
		mach_msg_header_t Head;
		/* start of the kernel processed data */
		mach_msg_body_t msgh_body;
		mach_msg_port_descriptor_t listener;
		/* end of the kernel processed data */
		NDR_record_t NDR;
		mach_msg_type_number_t sessionOffset; /* MiG doesn't use it */
		mach_msg_type_number_t sessionCnt;
		char session[4096];
	} Request __attribute__((unused));
#ifdef  __MigPackStructs
#pragma pack()
#endif

#ifdef  __MigPackStructs
#pragma pack(4)
#endif
	typedef struct {
		mach_msg_header_t Head;
		NDR_record_t NDR;
		kern_return_t RetCode;
		mach_msg_trailer_t trailer;
	} Reply __attribute__((unused));
#ifdef  __MigPackStructs
#pragma pack()
#endif

#ifdef  __MigPackStructs
#pragma pack(4)
#endif
	typedef struct {
		mach_msg_header_t Head;
		NDR_record_t NDR;
		kern_return_t RetCode;
	} __Reply __attribute__((unused));
#ifdef  __MigPackStructs
#pragma pack()
#endif
	/*
	 * typedef struct {
	 * 	mach_msg_header_t Head;
	 * 	NDR_record_t NDR;
	 * 	kern_return_t RetCode;
	 * } mig_reply_error_t;
	 */

	union {
		Request In;
		Reply Out;
	} Mess;

	Request *InP = &Mess.In;
	Reply *Out0P = &Mess.Out;

	mach_msg_return_t msg_result;
	unsigned int msgh_size;

#ifdef	__MIG_check__Reply__register_completion_listener_t__defined
	kern_return_t check_result;
#endif	/* __MIG_check__Reply__register_completion_listener_t__defined */

	__DeclareSendRpc(133702, "register_completion_listener")

#if	UseStaticTemplates
	const static mach_msg_port_descriptor_t listenerTemplate = {
		/* name = */		MACH_PORT_NULL,
		/* pad1 = */		0,
		/* pad2 = */		0,
		/* disp = */		19,
		/* type = */		MACH_MSG_PORT_DESCRIPTOR,
	};
#endif	/* UseStaticTemplates */

	InP->msgh_body.msgh_descriptor_count = 1;
#if	UseStaticTemplates
	InP->listener = listenerTemplate;
	InP->listener.name = listener;
#else	/* UseStaticTemplates */
	InP->listener.name = listener;
	InP->listener.disposition = 19;
	InP->listener.type = MACH_MSG_PORT_DESCRIPTOR;
#endif	/* UseStaticTemplates */

	InP->NDR = NDR_record;

#ifdef USING_MIG_STRNCPY_ZEROFILL
	if (mig_strncpy_zerofill != NULL) {
		InP->sessionCnt = mig_strncpy_zerofill(InP->session, session, 4096);
	} else {
#endif /* USING_MIG_STRNCPY_ZEROFILL */
		InP->sessionCnt = mig_strncpy(InP->session, session, 4096);
#ifdef USING_MIG_STRNCPY_ZEROFILL
	}
#endif /* USING_MIG_STRNCPY_ZEROFILL */

	msgh_size = (mach_msg_size_t)(sizeof(Request) - 4096) + (_WALIGN_(InP->sessionCnt));
	InP->Head.msgh_bits = MACH_MSGH_BITS_COMPLEX|
		MACH_MSGH_BITS(19, MACH_MSG_TYPE_MAKE_SEND_ONCE);
	/* msgh_size passed as argument */
	InP->Head.msgh_request_port = server;
	InP->Head.msgh_reply_port = mig_get_reply_port();
	InP->Head.msgh_id = 133702;
	InP->Head.msgh_reserved = 0;
	
/* BEGIN VOUCHER CODE */

#ifdef USING_VOUCHERS
	if (voucher_mach_msg_set != NULL) {
		voucher_mach_msg_set(&InP->Head);
	}
#endif // USING_VOUCHERS
	
/* END VOUCHER CODE */

	__BeforeSendRpc(133702, "register_completion_listener")
	msg_result = mach_msg(&InP->Head, MACH_SEND_MSG|MACH_RCV_MSG|MACH_MSG_OPTION_NONE, msgh_size, (mach_msg_size_t)sizeof(Reply), InP->Head.msgh_reply_port, MACH_MSG_TIMEOUT_NONE, MACH_PORT_NULL);
	__AfterSendRpc(133702, "register_completion_listener")
	if (msg_result != MACH_MSG_SUCCESS) {
		__MachMsgErrorWithoutTimeout(msg_result);
		{ return msg_result; }
	}


#if	defined(__MIG_check__Reply__register_completion_listener_t__defined)
	check_result = __MIG_check__Reply__register_completion_listener_t((__Reply__register_completion_listener_t *)Out0P);
	if (check_result != MACH_MSG_SUCCESS)
		{ return check_result; }
#endif	/* defined(__MIG_check__Reply__register_completion_listener_t__defined) */

	return KERN_SUCCESS;
}

#if ( __MigTypeCheck )
#if __MIG_check__Reply__shelld_subsystem__
#if !defined(__MIG_check__Reply__unregister_completion_listener_t__defined)
#define __MIG_check__Reply__unregister_completion_listener_t__defined

mig_internal kern_return_t __MIG_check__Reply__unregister_completion_listener_t(__Reply__unregister_completion_listener_t *Out0P)
{

	typedef __Reply__unregister_completion_listener_t __Reply __attribute__((unused));
	if (Out0P->Head.msgh_id != 133803) {
	    if (Out0P->Head.msgh_id == MACH_NOTIFY_SEND_ONCE)
		{ return MIG_SERVER_DIED; }
	    else
		{ return MIG_REPLY_MISMATCH; }
	}

#if	__MigTypeCheck
	if ((Out0P->Head.msgh_bits & MACH_MSGH_BITS_COMPLEX) ||
	    (Out0P->Head.msgh_size != (mach_msg_size_t)sizeof(__Reply)))
		{ return MIG_TYPE_ERROR ; }
#endif	/* __MigTypeCheck */

	{
		return Out0P->RetCode;
	}
}
#endif /* !defined(__MIG_check__Reply__unregister_completion_listener_t__defined) */
#endif /* __MIG_check__Reply__shelld_subsystem__ */
#endif /* ( __MigTypeCheck ) */


/* Routine unregister_completion_listener */
mig_external kern_return_t unregister_completion_listener
(
	mach_port_t server,
	string session
)
{

#ifdef  __MigPackStructs
#pragma pack(4)
#endif
	typedef struct {
		mach_msg_header_t Head;
		NDR_record_t NDR;
		mach_msg_type_number_t sessionOffset; /* MiG doesn't use it */
		mach_msg_type_number_t sessionCnt;
		char session[4096];
	} Request __attribute__((unused));
#ifdef  __MigPackStructs
#pragma pack()
#endif

#ifdef  __MigPackStructs
#pragma pack(4)
#endif
	typedef struct {
		mach_msg_header_t Head;
		NDR_record_t NDR;
		kern_return_t RetCode;
		mach_msg_trailer_t trailer;
	} Reply __attribute__((unused));
#ifdef  __MigPackStructs
#pragma pack()
#endif

#ifdef  __MigPackStructs
#pragma pack(4)
#endif
	typedef struct {
		mach_msg_header_t Head;
		NDR_record_t NDR;
		kern_return_t RetCode;
	} __Reply __attribute__((unused));
#ifdef  __MigPackStructs
#pragma pack()
#endif
	/*
	 * typedef struct {
	 * 	mach_msg_header_t Head;
	 * 	NDR_record_t NDR;
	 * 	kern_return_t RetCode;
	 * } mig_reply_error_t;
	 */

	union {
		Request In;
		Reply Out;
	} Mess;

	Request *InP = &Mess.In;
	Reply *Out0P = &Mess.Out;

	mach_msg_return_t msg_result;
	unsigned int msgh_size;

#ifdef	__MIG_check__Reply__unregister_completion_listener_t__defined
	kern_return_t check_result;
#endif	/* __MIG_check__Reply__unregister_completion_listener_t__defined */

	__DeclareSendRpc(133703, "unregister_completion_listener")

	InP->NDR = NDR_record;

#ifdef USING_MIG_STRNCPY_ZEROFILL
	if (mig_strncpy_zerofill != NULL) {
		InP->sessionCnt = mig_strncpy_zerofill(InP->session, session, 4096);
	} else {
#endif /* USING_MIG_STRNCPY_ZEROFILL */
		InP->sessionCnt = mig_strncpy(InP->session, session, 4096);
#ifdef USING_MIG_STRNCPY_ZEROFILL
	}
#endif /* USING_MIG_STRNCPY_ZEROFILL */

	msgh_size = (mach_msg_size_t)(sizeof(Request) - 4096) + (_WALIGN_(InP->sessionCnt));
	InP->Head.msgh_bits =
		MACH_MSGH_BITS(19, MACH_MSG_TYPE_MAKE_SEND_ONCE);
	/* msgh_size passed as argument */
	InP->Head.msgh_request_port = server;
	InP->Head.msgh_reply_port = mig_get_reply_port();
	InP->Head.msgh_id = 133703;
	InP->Head.msgh_reserved = 0;
	
/* BEGIN VOUCHER CODE */

#ifdef USING_VOUCHERS
	if (voucher_mach_msg_set != NULL) {
		voucher_mach_msg_set(&InP->Head);
	}
#endif // USING_VOUCHERS
	
/* END VOUCHER CODE */

	__BeforeSendRpc(133703, "unregister_completion_listener")
	msg_result = mach_msg(&InP->Head, MACH_SEND_MSG|MACH_RCV_MSG|MACH_MSG_OPTION_NONE, msgh_size, (mach_msg_size_t)sizeof(Reply), InP->Head.msgh_reply_port, MACH_MSG_TIMEOUT_NONE, MACH_PORT_NULL);
	__AfterSendRpc(133703, "unregister_completion_listener")
	if (msg_result != MACH_MSG_SUCCESS) {
		__MachMsgErrorWithoutTimeout(msg_result);
		{ return msg_result; }
	}


#if	defined(__MIG_check__Reply__unregister_completion_listener_t__defined)
	check_result = __MIG_check__Reply__unregister_completion_listener_t((__Reply__unregister_completion_listener_t *)Out0P);
	if (check_result != MACH_MSG_SUCCESS)
		{ return check_result; }
#endif	/* defined(__MIG_check__Reply__unregister_completion_listener_t__defined) */

	return KERN_SUCCESS;
}
